const articles = [
  {
    id: 1,
    type: "Article",
    date: "March 2021",
    author: "Ameya Dehade",
    title: "Machine Learning Website",
    subtext:
      "Our model uses the Iterative Proportional Fitting Procedure (IPFP), a classical algorithm in computer science that performs data scaling based on current datasets, to create a mobility network containing information about the number of individuals (agents) traveling from each Census Block Group (CBG) to...",
    href: "/developmentblog/Post1",
    img: "https://i.postimg.cc/pXP5BBDC/blogpost-Pic1.png?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    //url: "https://covidweb.isi.jhu.edu/developmentblog/Post1",
  },
  {
    id: 2,
    type: "Article",
    date: "March 2021",
    author: "Ameya Dehade",
    title: "Simulation Development",
    subtext:
      "Currently, the simulation team is working on the severity risk matrix, which is how they decide whether an agent is asymptomatic, mild, severe, or critical after their incubation period is over after exposure. The figure below illustrates the different stages before reaching the severity risk matrix determination...",
    href: "/developmentblog/Post2",
    img: "https://i.postimg.cc/90w2dKL0/blogpost-Pic4.png?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
    //url: "https://covidweb.isi.jhu.edu/developmentblog/Post1",
  },
  {
    id: 3,
    type: "Article",
    date: "July 2021",
    author: "Serena Chan",
    title: "Wells-Riley Equation",
    subtext: "The Delineo simulation uses the Wells-Riley Equation to simulate how a disease will spread in any given city. The equation and the simulation focus on places of interest (POI) that include grocery stores, places of worship, and other types of gathering areas where a person might get infected. We apply...",
    href: "/developmentblog/Post3",
    img: "https://i.postimg.cc/Y97qZcxc/1.jpg",
  },
  {
    id: 8,
    type: "News",
    date: "Date 1",
    author: "Author",
    title: "React Router",
    subtext: "Blog 1 Description",
    href: "/developmentblog/date-3",
    img: "https://images.pexels.com/photos/325111/pexels-photo-325111.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
  },
  {
    id: 9,
    type: "News",
    date: "Date 2",
    author: "Author",
    title: "React Router",
    subtext: "Blog 2 Description",
    href: "/developmentblog/date-3",
    img: "https://images.pexels.com/photos/325111/pexels-photo-325111.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
  },
  {
    id: 10,
    type: "News",
    date: "Date 3",
    author: "Author",
    title: "React Router",
    subtext: "Blog 3 Description",
    href: "/developmentblog/date-3",
    img: "https://images.pexels.com/photos/325111/pexels-photo-325111.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
  },
];
export default articles;
